language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# NOT_CRAN and options in .Rprofile are workarounds for "cyclic dependency check" error
# see https://github.com/travis-ci/travis-ci/issues/4125
env:
  global:
    - NOT_CRAN=true

# update all packages before install
# (should solve problem of stale packages in ubuntu R distro)
# see https://github.com/travis-ci/travis-ci/issues/6850
before_install: 
  - Rscript -e 'update.packages(ask = FALSE)'
